if exists (select * from INFORMATION_SCHEMA.TABLES where TABLE_NAME = 'EOA_BACKUP_1')
    BEGIN
		drop table EOA_BACKUP_1
    END
    
GO

if exists (select * from INFORMATION_SCHEMA.TABLES where TABLE_NAME = 'EOA_BACKUP_2')
    BEGIN
		drop table EOA_BACKUP_2
    END
    
GO

if exists (select * from INFORMATION_SCHEMA.TABLES where TABLE_NAME = 'EOA_BACKUP_3')
    BEGIN
		drop table EOA_BACKUP_3
    END
    
GO

if exists (select * from INFORMATION_SCHEMA.TABLES where TABLE_NAME = 'EOA_BACKUP_4')
    BEGIN
		drop table EOA_BACKUP_4
    END
    
GO

-- columns not to break a backup

IF NOT EXISTS( SELECT * 
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'SALESORD_HDR' AND  COLUMN_NAME = 'X_CARRIER') 
BEGIN 
	ALTER TABLE SALESORD_HDR 
	ADD X_CARRIER varchar(100) NULL
END

GO

IF NOT EXISTS( SELECT * 
	FROM INFORMATION_SCHEMA.COLUMNS 
	WHERE TABLE_NAME = 'SALESORD_LINES' AND  COLUMN_NAME = 'X_ACTION') 
BEGIN 
	ALTER TABLE SALESORD_LINES 
	ADD X_ACTION INT NULL
END

GO

IF NOT EXISTS( SELECT * 
	FROM INFORMATION_SCHEMA.COLUMNS 
	WHERE TABLE_NAME = 'EOA_SETTINGS' AND  COLUMN_NAME = '30_LABEL_PRINTER') 
BEGIN 
	ALTER TABLE EOA_SETTINGS 
	ADD [30_LABEL_PRINTER] varchar(255)
END

GO

----------------------------------

SELECT SEQNO
	   ,X_DISPATCHSTATUS
	   ,X_DISPATCHMETHOD
	   ,X_DUETIME
	   ,X_DIFOT_TIMESTAMP
	   ,X_PICKDATE
	   ,X_CARRIER
INTO EOA_BACKUP_1
FROM SALESORD_HDR

GO

SELECT SEQNO
	   ,X_DIFOT_STATUS
	   ,X_SCHEDULE_TIMESTAMP
	   ,X_DIFOT_TIMESTAMP
	   ,X_DISPATCHMETHOD
	   ,X_DIFOT_NOTE
INTO EOA_BACKUP_2
FROM DR_TRANS

GO

SELECT SEQNO
	   ,X_ACTION
INTO EOA_BACKUP_4
FROM SALESORD_LINES

GO

UPDATE EOA_BACKUP_1
SET X_DISPATCHMETHOD = NULL
WHERE X_DISPATCHMETHOD = 'G'

GO

UPDATE EOA_BACKUP_1
SET X_DISPATCHSTATUS = 'TP-PICK'
WHERE X_DISPATCHSTATUS = 'TP'

GO

UPDATE EOA_BACKUP_2
SET X_DISPATCHMETHOD = NULL
WHERE X_DISPATCHMETHOD = 'G'

GO

if exists (select * from INFORMATION_SCHEMA.TABLES where TABLE_NAME = 'EOA_SETTINGS')
    BEGIN
		SELECT PRINTER_NAME, LABEL_PRINTER, [30_LABEL_PRINTER]
		INTO EOA_BACKUP_3
		FROM EOA_SETTINGS
    END
    
GO