if exists (select * from INFORMATION_SCHEMA.TABLES where TABLE_NAME = 'EOA_BACKUP_1')
    BEGIN
		drop table EOA_BACKUP_1
    END
    
GO

if exists (select * from INFORMATION_SCHEMA.TABLES where TABLE_NAME = 'EOA_BACKUP_2')
    BEGIN
		drop table EOA_BACKUP_2
    END
    
GO

if exists (select * from INFORMATION_SCHEMA.TABLES where TABLE_NAME = 'EOA_BACKUP_3')
    BEGIN
		drop table EOA_BACKUP_3
    END
    
GO

if exists (select * from INFORMATION_SCHEMA.TABLES where TABLE_NAME = 'EOA_BACKUP_4')
    BEGIN
		drop table EOA_BACKUP_4
    END
    
GO

----------------------------------

SELECT SEQNO
	   ,X_DISPATCHSTATUS
	   ,X_DISPATCHMETHOD
	   ,X_DUETIME
	   ,X_DIFOT_TIMESTAMP
	   ,X_PICKDATE
	   ,X_CARRIER
INTO EOA_BACKUP_1
FROM SALESORD_HDR

GO

SELECT SEQNO
	   ,X_DIFOT_STATUS
	   ,X_SCHEDULE_TIMESTAMP
	   ,X_DIFOT_TIMESTAMP
	   ,X_DISPATCHMETHOD
	   ,X_DIFOT_NOTE
INTO EOA_BACKUP_2
FROM DR_TRANS

GO

SELECT SEQNO
	   ,X_ACTION
INTO EOA_BACKUP_4
FROM SALESORD_LINES

GO

if exists (select * from INFORMATION_SCHEMA.TABLES where TABLE_NAME = 'EOA_SETTINGS')
    BEGIN
		SELECT PRINTER_NAME, LABEL_PRINTER, [30_LABEL_PRINTER], PICK_LABEL_PRINTER
		INTO EOA_BACKUP_3
		FROM EOA_SETTINGS
    END
    
GO